### ISSUE TITLE
Check class instance state is mutated

### ISSUE THREAD

**Issue by andygout** [Financial-Times/n-health#209]
The `categoryInCheckName` function that appears in [these lines](https://github.com/Financial-Times/n-health/blob/main/main.js#L7-L10) and below mutates the state of the Check class instance (the `check` argument).

```js
function categoryInCheckName(healthCheck, check){
	check.name = healthCheck.name + ': ' + check.name;
	return check;
}
```

If a check invokes the `asArray()` method more than once then the `healthCheck.name` value will keep getting prefixed to the start of the new check name, resulting in check names such as:

**Backend key: Backend key: The shared backend key has been rotated recently**

when the desired result is:

**Backend key: The shared backend key has been rotated recently**

There are legitimate reasons why `asArray()` may be called twice and cause this effect - this was happening in `next-health` and was fixed by this PR: https://github.com/Financial-Times/next-health/pull/360.

The preferred solution would be to fix this issue at source and allow `asArray()` to be invoked multiple times without affecting the state of the Check class instances property values.

**Comment by rowanmanning** [comment]
I know I said to open this and it's a well written issue, Andy. Just probably never gonna get to it and we're slowly phasing out this kind of health check tbh. If you ever feel like doing it then feel free to PR but doing some cleaning and closing old issues/PRs
