### ISSUE TITLE
Update README to mention how slack notifications work

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/n-health#65]
See: https://github.com/Financial-Times/n-health/blob/master/test/fixtures/serviceRegistryFixture.json#L1511 for example

**Comment by andygnewman** [comment]
@adambraimbridge I think that the slack notifications are actually controlled from [next-service-registry](https://github.com/Financial-Times/next-service-registry). The file here is just a test fixture (though confusingly looks too realistic for a test fixture)
