### ISSUE TITLE
Graphite healthcheck could show the actual values/results as it's output

### ISSUE THREAD

**Issue by adgad** [Financial-Times/n-health#86]
Current: 
`No threshold error detected in graphite data for asPercent(summarize(sumSeries(next.heroku.front-page.web*EU.express..res.status.{500,503,504}.count), '10min', 'sum', true), summarize(sumSeries(next.heroku.front-page.web__EU.express..res.status..count), '10min', 'sum', true)).`

Could be something like :
`Current value of 0.04% is below the threshold of 1%. Query: <link to graphite query>`

**Comment by rowanmanning** [comment]
We removed graphite checks in the latest major version so this is a won't-fix
