### ISSUE TITLE
Add ids to check class constructor

### ISSUE THREAD

**Issue by kateloschinina** [Financial-Times/n-health#89]
<img width="598" alt="screen shot 2018-05-24 at 12 37 21" src="https://user-images.githubusercontent.com/10063385/40488832-8f99efca-5f5f-11e8-9d97-ae5f305ae4d1.png">

Can we figure out what is the best way to add these ids so that we don't need to change it in every app?

**Comment by rowanmanning** [comment]
Closing this just because it's been years and nobody else has asked for it. We're slowly phasing out use of health checks anyway
